library(readr)
sensor_readings_2 <- read_csv("AllData/sensor_readings_2.data", col_names = c('SD_front', 'SD_left', 'class'))
sensor_readings_4 <- read_csv("AllData/sensor_readings_4.data", col_names = FALSE)
sensor_readings_24 <- read_csv("AllData/sensor_readings_24.data", col_names = FALSE)
colnames(sensor_readings_4)[5] <- "class"
colnames(sensor_readings_24)[25] <- "class"
colnames(sensor_readings_4)[1:4] <- c("y1","y2","y3", "y4")
usableData <- cbind(sensor_readings_24[,1:24], sensor_readings_2[,1:2], sensor_readings_4[,1:4], sensor_readings_24[,25])
table(usableData$class)
apply(usableData, 2, function(x) any(is.na(x)))
usableData <- na.omit(usableData)

B<-5
ERRMAT<-matrix(0,B,8)

ctrl<-trainControl(method="cv",summaryFunction=multiClassSummary)

for (b in (1:B)) {
  inTrainRows <- createDataPartition(usableData$class,p=0.7,list=FALSE)
  trainData <- usableData[inTrainRows,]
  trainData$class <- as.factor(trainData$class)
  testData <-  usableData[-inTrainRows,-31]
  trainDataY <- as.factor(usableData$class[inTrainRows])
  testDataY <- as.factor(usableData$class[-inTrainRows])
  fit<-train(class~.,data=trainData,method="rpart",tuneLength=15,trControl=ctrl)
  print('fit 1')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,1]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="ranger",tuneLength=15,trControl=ctrl)
  print('fit 2')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,2]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="knn",tuneLength=15,trControl=ctrl)
  print('fit 3')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,3]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="lda",tuneLength=15,trControl=ctrl)
  print('fit 4')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,4]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="qda",tuneLength=15,trControl=ctrl)
  print('fit 5')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,5]<- length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="pda",tuneLength=15,trControl=ctrl)
  print('fit 6')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,6]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="nb",tuneLength=15,trControl=ctrl)
  print('fit 7')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,7]<-length(pp[pp!=testDataY])/length(pp)
  fit<-train(class~.,data=trainData,method="mda",tuneLength=15,trControl=ctrl)
  print('fit 8')
  pp<-predict(fit,newdata=testData,type="raw")
  ERRMAT[b,8]<-length(pp[pp!=testDataY])/length(pp)
  print(b)
}
par(mfrow=c(1,1))
boxplot(ERRMAT,names=c("CART","RF","knn","lda","qda","pda","nb","mda"))        
